apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patchesStrategicMerge:
  - replica-patch.yaml
images:
  - name: dogukanngumus/k8s-hero-app
    newTag: placeholder-prod # CI/CD burayı ezecek